# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-03 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='checked_in',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='checked_out',
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('cancelled', 'Cancelled'), ('in', 'Checked in'), ('out', 'Checked out'), ('help', 'Requesting Services')], default='reserved', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
